# Generated by Django 5.1.6 on 2025-03-21 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='duration',
            field=models.IntegerField(default=365, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(365)]),
        ),
    ]
