# Generated by Django 5.1.6 on 2025-03-24 08:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Signup Code',
                'verbose_name_plural': 'Signup Codes',
                'ordering': ['created'],
            },
        ),
    ]
